sources:
  - type: maven
    path: agent/pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
    advertise: false
  - type: maven
    path: verifier/pom.xml
    modules:
      - integration_tests
      - maven_central
version:
  fromSource: verifier/pom.xml
excludes:
  - "E-PK-CORE-17: Missing required file: '.github/workflows/project-keeper-verify.yml'"
  - "E-PK-CORE-17: Missing required file: '.github/workflows/project-keeper.sh'"
  - regex: "E-PK-CORE-53: The dependencies.md file has outdated content.*"
