sources:
  - type: maven
    path: agent/pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
    advertise: false
  - type: maven
    path: verifier/pom.xml
    modules:
      - lombok
      - integration_tests
      - maven_central
version:
  fromSource: verifier/pom.xml

