sources:
  - type: maven
    path: pom.xml
  - type: maven
    path: agent/pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
    advertise: false
  - type: maven
    path: verifier/pom.xml
    modules:
      - integration_tests
      - maven_central
version:
  fromSource: verifier/pom.xml
build:
  runnerOs: ubuntu-20.04
  exasolDbVersions:
    - "8.25.0"
    - "7.1.25"
